/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/arama`; params?: Router.UnknownInputParams; } | { pathname: `/fiyat-takibi`; params?: Router.UnknownInputParams; } | { pathname: `/stok-takibi`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/giris` | `/giris`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/kayit` | `/kayit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bildirimler` | `/bildirimler`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/karsilastirma` | `/karsilastirma`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listelerim` | `/listelerim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/urun/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/arama`; params?: Router.UnknownOutputParams; } | { pathname: `/fiyat-takibi`; params?: Router.UnknownOutputParams; } | { pathname: `/stok-takibi`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/giris` | `/giris`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/kayit` | `/kayit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bildirimler` | `/bildirimler`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/karsilastirma` | `/karsilastirma`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/listelerim` | `/listelerim`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/urun/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/arama${`?${string}` | `#${string}` | ''}` | `/fiyat-takibi${`?${string}` | `#${string}` | ''}` | `/stok-takibi${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/giris${`?${string}` | `#${string}` | ''}` | `/giris${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/kayit${`?${string}` | `#${string}` | ''}` | `/kayit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bildirimler${`?${string}` | `#${string}` | ''}` | `/bildirimler${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/karsilastirma${`?${string}` | `#${string}` | ''}` | `/karsilastirma${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/listelerim${`?${string}` | `#${string}` | ''}` | `/listelerim${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/arama`; params?: Router.UnknownInputParams; } | { pathname: `/fiyat-takibi`; params?: Router.UnknownInputParams; } | { pathname: `/stok-takibi`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/giris` | `/giris`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/kayit` | `/kayit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bildirimler` | `/bildirimler`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/karsilastirma` | `/karsilastirma`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listelerim` | `/listelerim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | `/urun/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/urun/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
